#Set in conf file
APIUID="YOURUID"
APIKEY="YOURPWD"

#You probably want to enter this from the command line
#CN="*.yourname.be"
#CERTTYPE="ComWild"
#PRIVKEY_PATH="/tmp/key.pem"
#FULLCHAIN_PATH="/tmp/fullchain.pem"

#You probably don't want to touch this
#API_URL="https://api.bNamed.net/API"
#AUTOPAY="true"
#RENEW_BEFORE_DAYS=19
#MAX_POLLS=20
#POLL_INTERVAL=60
